database:
  driverClass: ${DEX_DATABASE_DRIVER_CLASS:-org.postgresql.Driver}
  user: ${DEX_DATABASE_USER:-dexter}
  password: ${DEX_DATABASE_PASSWORD:-dexter}
  url: ${DEX_DATABASE_URL:-jdbc:postgresql://postgres:5432/dexter}
  properties:
    charSet: ${DEX_DATABASE_PROPERTIES_CHAR_SET:-UTF-8}
  maxWaitForConnection: ${DEX_DATABASE_MAX_WAIT_FOR_CONNECTION:-1s}
  validationQueryTimeout: ${DEX_DATABASE_VALIDATION_QUERY_TIMEOUT:-3s}
  minSize: ${DEX_DATABASE_MIN_SIZE:-8}
  maxSize: ${DEX_DATABASE_MAX_SIZE:-32}
  checkConnectionWhileIdle: ${DEX_DATABASE_CHECK_CONNECTION_WHILE_IDLE:-false}
  evictionInterval: ${DEX_DATABASE_EVICTION_INTERVAL:-10s}

flyway:
  cleanDisabled: ${DEX_FLYWAY_CLEAN_DISABLED:-true}
  locations: ${DEX_FLYWAY_LOCATIONS:-['filesystem:backend/db']}

externalBaseUrl: ${DEX_EXTERNAL_BASE_URL:-http://localhost:8080}

logging:
  level: INFO
  loggers:
    nl.knaw.huc: DEBUG
    org: WARN
    org.glassfish: ERROR

server:
  applicationConnectors:
    - type: http
      port: ${DEX_SERVER_PORT:-8080}

