server:
  applicationConnectors:
    - type: http
      port: ${DEX_SERVER_PORT:-8080}

externalBaseUrl: ${DEX_EXTERNAL_BASE_URL:-http://localhost:8080}

logging:
  level: INFO
  loggers:
    nl.knaw.huc: DEBUG
    org: WARN
    org.glassfish: ERROR