database:
  driverClass: ${DEX_DATABASE_DRIVER_CLASS:-org.postgresql.Driver}
  user: ${DEX_DATABASE_USER:-dexter}
  password: ${DEX_DATABASE_PASSWORD:-dexter}
  url: ${DEX_DATABASE_URL:-jdbc:postgresql://postgres:5432/dexter}
  properties:
    charSet: ${DEX_DATABASE_PROPERTIES_CHAR_SET:-UTF-8}
  maxWaitForConnection: ${DEX_DATABASE_MAX_WAIT_FOR_CONNECTION:-1s}
  validationQueryTimeout: ${DEX_DATABASE_VALIDATION_QUERY_TIMEOUT:-3s}
  minSize: ${DEX_DATABASE_MIN_SIZE:-8}
  maxSize: ${DEX_DATABASE_MAX_SIZE:-32}
  checkConnectionWhileIdle: ${DEX_DATABASE_CHECK_CONNECTION_WHILE_IDLE:-false}
  evictionInterval: ${DEX_DATABASE_EVICTION_INTERVAL:-10s}

externalBaseUrl: ${DEX_EXTERNAL_BASE_URL:-http://localhost:8080}

flyway:
  baselineOnMigrate: ${DEX_FLYWAY_BASELINE_ON_MIGRATE:-false}
  baselineVersion: ${DEX_FLYWAY_BASELINE_VERSION:-'0'}
  cleanDisabled: ${DEX_FLYWAY_CLEAN_DISABLED:-true}
  locations: ${DEX_FLYWAY_LOCATIONS:-['filesystem:db/migration']}

logging:
  level: INFO
  loggers:
    nl.knaw.huc: DEBUG
    org: WARN
    org.glassfish: ERROR

root:
  user: ${DEX_ROOT_USER:-root}
  pass: ${DEX_ROOT_PASS:-d33d33}

server:
  applicationConnectors:
    - type: http
      port: ${DEX_SERVER_PORT:-8080}