FROM node:18.9.0-alpine as build

WORKDIR /dexter
COPY ./package.json /dexter/package.json

RUN npm install

COPY . .
RUN npm run build

FROM nginx:1.25.3-alpine3.18
COPY --from=build /dexter/dist /usr/share/nginx/html
EXPOSE 80
