FROM node:18.9.0-alpine as build

WORKDIR /dexter
COPY ./package.json /dexter/package.json

RUN npm install

COPY . .
RUN --mount=type=cache,target=./node_modules/.cache/webpack npm run build

FROM nginx:alpine
COPY --from=build /dexter/dist /usr/share/nginx/html
EXPOSE 80
