export enum ACTIONS {
    SET_COLLECTIONS = "SET_COLLECTIONS",
    SET_SELECTEDCOLLECTION = "SET_SELECTEDCOLLECTION",
    SET_EDITCOLMODE = "SET_EDITCOLMODE",
    SET_TOEDITCOL = "SET_TOEDITCOL",
    SET_SOURCES = "SET_SOURCES"
}