export enum ACTIONS {
    SET_COLLECTIONS = "SET_COLLECTIONS",
    SET_FILTEREDCOLLECTIONS = "SET_FILTEREDCOLLECTIONS",
    SET_SELECTEDCOLLECTION = "SET_SELECTEDCOLLECTION",
    SET_EDITCOLMODE = "SET_EDITCOLMODE",
    SET_TOEDITCOL = "SET_TOEDITCOL",
    SET_SOURCES = "SET_SOURCES",
    SET_FILTEREDSOURCES = "SET_FILTEREDSOURCES",
    SET_SELECTEDSOURCE = "SET_SELECTEDSOURCE",
    SET_EDITSOURCEMODE = "SET_EDITSOURCEMODE",
    SET_TOEDITSOURCE = "SET_TOEDITSOURCE",
    SET_ERROR = "SET_ERROR"
}